server:
  port: 8086

spring:
  application:
    name: evaluation-task
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/evaluation
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
